/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Days: typeof import('./src/components/Days.vue')['default']
    Heart: typeof import('./src/components/Heart.vue')['default']
    IBiInfinity: typeof import('~icons/bi/infinity')['default']
    IIconParkOutlinePeoples: typeof import('~icons/icon-park-outline/peoples')['default']
    IMdiLightRss: typeof import('~icons/mdi-light/rss')['default']
    ISolarAltArrowDownLineDuotone: typeof import('~icons/solar/alt-arrow-down-line-duotone')['default']
    ISolarAltArrowUpLineDuotone: typeof import('~icons/solar/alt-arrow-up-line-duotone')['default']
    ISolarInfinityLinear: typeof import('~icons/solar/infinity-linear')['default']
    OpenIcon: typeof import('./src/components/OpenIcon.vue')['default']
    ParticipantsList: typeof import('./src/components/participantsList.vue')['default']
    ParticipantsTitle: typeof import('./src/components/participantsTitle.vue')['default']
    ScheduleDetail: typeof import('./src/components/ScheduleDetail.vue')['default']
    ScheduleRow: typeof import('./src/components/ScheduleRow.vue')['default']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
