/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Days: typeof import('./src/components/Days.vue')['default']
    Heart: typeof import('./src/components/Heart.vue')['default']
    ParticipantsList: typeof import('./src/components/participantsList.vue')['default']
    ParticipantsTitle: typeof import('./src/components/participantsTitle.vue')['default']
    ScheduleDetail: typeof import('./src/components/ScheduleDetail.vue')['default']
    ScheduleRow: typeof import('./src/components/ScheduleRow.vue')['default']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
