/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ScheduleDetail: typeof import('./src/components/ScheduleDetail.vue')['default']
    ScheduleTable: typeof import('./src/components/ScheduleTable.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    ZTable: typeof import('./src/components/ScheduleTable.vue')['default']
  }
}
