services:
  sdash:
    build:
      context: .
    volumes:
      - ./dist:/static
      - ./database:/database
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - STATIC_DIR=/static
      - DB_DIR=/database
    develop:
      watch:
        - action: rebuild
          path: package.json
  caddy:
    image: caddy:latest  # Добавляем образ Caddy
    volumes:
      - ./Caddy/Caddyfile.txt:/etc/caddy/Caddyfile:ro
      - ./Caddy/caddy_data:/data
      - ./Caddy/caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./Caddy/Caddyfile.txt