version: "3.8"

services:
  app:
    build:
      context: .
    volumes:
      - ./server:/app # Монтируем весь проект в контейнер, чтобы изменения файлов автоматически применялись
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production